# Generated by Django 4.1.1 on 2022-10-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='topic',
            new_name='movie',
        ),
    ]
