# Generated by Django 4.1.1 on 2022-10-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date',
            new_name='aika',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='arvosana',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='movie',
            new_name='elokuva',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='bad',
            new_name='miinukset',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='good',
            new_name='plussat',
        ),
    ]
