# Generated by Django 4.1.1 on 2022-10-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_date_feedback_aika_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name']},
        ),
    ]
