# Generated by Django 4.1.1 on 2022-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='arvosana',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
